# Generated by Django 5.0.1 on 2024-02-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('user_ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
