# Generated by Django 5.0.1 on 2024-02-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0003_alter_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='endTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='startTime',
            field=models.DateTimeField(null=True),
        ),
    ]
