# Generated by Django 5.0.1 on 2024-02-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0004_task_endtime_task_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='endTime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='startTime',
            field=models.TimeField(null=True),
        ),
    ]
