# Generated by Django 5.0.1 on 2024-02-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0005_alter_task_date_alter_task_endtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='user_ID',
            field=models.CharField(max_length=32),
        ),
    ]
