# Generated by Django 5.0.1 on 2024-02-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0006_alter_task_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='remind_date',
            field=models.DateField(null=True),
        ),
    ]
